config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'spotify/search'
  
  resources :tracks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :playlists # Adding new 7 standard routes

	root to: 'tracks#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	# Empty fields are not allowed
	validates_presence_of :name, :number_of_votes
end

app/models/track.rb
class Track < ApplicationRecord
	# Empty 'track' fields are not allowed
	validates_presence_of :title, :artist, :album
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
	before_action :authenticate_user!
	# Save in var all the playlists, then use it in the View to show the info
	# @ ==> instance var access to Playlist MODEL and gets all of the lists
	def index
		@playlists = Playlist.all
	end

	# Save the playlists to show every one we want using the respective id
	def show
		@playlist = Playlist.find(params[:id])
	end

	# New give us a form to create a new element
	def new
		@playlist = Playlist.new
	end

	# Create the element in DataBase
	# Passed params are already filtered
	def create
		@playlist = Playlist.new(playlist_params)
		if @playlist.save
			redirect_to @playlist
		else
			render :new
		end
	end

	private	
	# White list with Accepted Params=name, number_of_votes
	def playlist_params
		params.require(:playlist).permit(:name, :number_of_votes)
	end
end

app/controllers/spotify_controller.rb
# require 'pry'
# require 'rspotify'
class SpotifyController < ApplicationController
  def search

  	# Extract parameter and save it
  	title = params[:title]
  	# validating the field 'title' isn't empty
  	if title
  		@results = RSpotify::Artist.search(title)
      @songs = RSpotify::Track.search(title)

      #@artist = search.first
  	end
  end

  # def search2
  #   title = params[:title]
  #   if title
  #     @songs = RSpotify::Track.search(title)
  #   end
  # end

  # private
  # def spotify_params
  # 	params.require(:spotify).permit(:name, :title, :search)
  # end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :album, :artist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Musicapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- <h1> Or something here.......2...</h1> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<html>
    <center>    <h1>*** MusicApp ***</h1>  </center>

<body>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>
    <center><h3>-.-. --- -. ..-. .. .- --..-- / ... .. . -. - . / .-.. .- / .- .-. -- --- -. .. .- / . -. / - ..- / -.-. --- .-. .- --.. -. .-.-.- .-.-.</h3></center>

app/views/playlists/index.html.erb
<h1>Todas las listas de reproducción</h1>

<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Number of votes</th>
		</tr>
	</thead>
	<tbody>
		<!-- ERB syntaxis to put Ruby Code, in '< % =', = indicates that Ruby Code will print on screen, that way I avoid it in the line of EACH method's -->
		<%  @playlists.each do |playlist| %>
		<tr> <!-- Each field shows the info of that elements-->
			<td><%= playlist.name %></td>
			<td><%= playlist.number_of_votes %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/playlists/new.html.erb
<!-- using helper 'form_for' here -->
<%= form_for(@playlist) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :number_of_votes %>
	<%= f.text_field :number_of_votes %>

	<%= f.submit %> 
<% end %>

app/views/playlists/show.html.erb
<p>---------------------------------------------------------------</p>
<p>
	<strong>Name: </strong>
	<!-- Show the name of a single playlist -->
	<%= @playlist.name %>
</p>

<p>
	<strong>Number of votes: </strong>
	<!-- Show the number of votes of a single playlist -->
	<%= @playlist.number_of_votes %>
</p>
<p>---------------------------------------------------------------</p>

app/views/spotify/search.html.erb
<!-- require 'rspotify' -->
<h1>Resultados de busqueda</h1>
<body>
    <%= link_to "Back", :controller => "tracks" %>
    <%= yield %>
</body>
<ul> 
	<h3>Artista:</h3>
	<% @results.each do |result| %> 
		<li><%= result.name %></li> 
	<% end %>
</ul>
<ul> 
	<h3>Canción:</h3>
	<% @songs.each do |song| %> 
		<li><%= song.name %></li> 
	<% end %>
</ul>

app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :album %>
    <%= form.text_field :album %>
  </div>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
 <p id="notice"><%= notice %></p>

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <h1>Tracks</h1>
    <!-- <%= select_date Date.today, :prefix => :start_date %> -->
    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>


<table>
  <thead>
<!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheets">
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.album %></td>
        <td><%= track.artist %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<!--     <%= radio_button_tag(:age, "child") %>
  <%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
  <%= label_tag(:age_adult, "I'm over 21") %> -->
  </tbody>
</table>

<br>

<%= link_to 'Add New Track', new_track_path %>

<%= form_tag(spotify_search_path, method: :get) do %>
  </p>
    <%= text_field_tag :title %>
    <%= submit_tag 'Search Artist' %>
  </p>
<% end %>
<%= form_tag(spotify_search_path, method: :get) do %>
  </p>
    <%= text_field_tag :title %>
    <%= submit_tag 'Search Song' %>
  </p>
<% end %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<center>  <!-- giving some of centered style here -->
	<p>
	  <strong>Title:</strong>
	  <%= @track.title %>
	</p>

	<p>
	  <strong>Album:</strong>
	  <%= @track.album %>
	</p>

	<p>
	  <strong>Artist:</strong>
	  <%= @track.artist %>
	</p>
</center>

<div align='center'>	<!-- another way to center this elements.... -->
	<%= link_to 'Edit', edit_track_path(@track) %> |
	<%= link_to 'Back', tracks_path %>
</div>